@startuml
skinparam componentStyle rectangle

[events] <--- [raw]
[objects / entities] <--- [raw]
[intermediates] <-- [raw]

[queries]
@enduml


@startuml
skinparam componentStyle rectangle

database operational_databases
database operational_databases_other_teams

[data_objects] ---> [raw]
[data_objects] ---> [raw_external]
[data_objects] -> [intermediates]
[intermediates] --> [raw]
[intermediates] --> [raw_external]

[raw] --> operational_databases
[raw_external] --> operational_databases_other_teams

[queries]
@enduml